### ISSUE TITLE
BUG:Chinese supports garbled characters

### ISSUE THREAD

**Issue by HarLin97** [nebula-contrib/nebula-console-intellij-plugin#1]
Query data returns garbled Chinese characters
![image](https://github.com/nebula-contrib/nebula-console-intellij-plugin/assets/29650805/8f7c40ea-b078-430d-a5ff-a019a7586fbc)

**Comment by awang12345** [comment]
Thanks for the feedback, I will fix it ASAP

**Comment by awang12345** [comment]
The bug has been fix in v1.0.2 version, please upgrade the  plugin to latest version
