### ISSUE TITLE
BUG:Attempting to connect LOG error message

### ISSUE THREAD

**Issue by HarLin97** [nebula-contrib/nebula-console-intellij-plugin#3]
![image](https://github.com/nebula-contrib/nebula-console-intellij-plugin/assets/29650805/c37f6dad-36b6-4937-a8d8-4785cd6fa96d)
Console
![image](https://github.com/nebula-contrib/nebula-console-intellij-plugin/assets/29650805/415c3623-f18f-48d8-85bd-43103841f0b6)
![image](https://github.com/nebula-contrib/nebula-console-intellij-plugin/assets/29650805/b813999c-098f-4bbb-a732-bdf51e7e2c1c)

**Comment by awang12345** [comment]
Thanks for the feedback, I will fix it ASAP

**Comment by awang12345** [comment]
The bug has been fix in v1.0.2 version, please upgrade the  plugin to latest version
